apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-app.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hello-app.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "hello-app.selectorLabels" . | nindent 4 }}
