# Default values for hello-app
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Application configuration
app:
  name: hello-world-flask
  environment: development
  version: "1.0.0"

# Image configuration
image:
  repository: us-central1-docker.pkg.dev/test-demo-123456-guillermo/staging-docker/hello-world-flask
  tag: "latest"
  pullPolicy: Always

# Replica configuration
replicaCount: 2

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: hello-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource configuration
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Liveness probe configuration
livenessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# Readiness probe configuration
readinessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Environment variables
env:
  - name: ENVIRONMENT
    value: "development"
  - name: APP_VERSION
    value: "1.0.0"
  - name: PORT
    value: "5000"

# Additional labels
labels: {}

# Additional annotations
annotations: {}

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Service account
serviceAccount:
  create: false
  name: ""
  annotations: {}
