# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "gcs" {
    bucket = "test-demo-123456-guillermo-tfstate-environments"
    prefix = "environments/production/terraform.tfstate"
  }
}
